name: Deploy Remotely
on:
  push:
    branches: [ master ]

jobs:
  Deploy-Remotely:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 18.19.0 to Build
      uses: actions/setup-node@v2
      with:
        node-version: 18.19.0

    # Install Angular CLI globally (optional if it's not in package.json)
    - name: Install Angular CLI
      run: npm install -g @angular/cli@16.2.12

    # Install dependencies
    - name: Change Directory
      run: cd /home/runner/work/bloggingWeb/

    - name: Install Dependencies
      run: npm install

    # Build the Angular app
    - name: Build Angular Application
      run: ng build --configuration=production


    # Transfer the build folder to the EC2 instance
    - name: Transfer Build Folder on EC2 Instance
      uses: easingthemes/ssh-deploy@v2.1.4
      env:
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
        REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
        REMOTE_USER: ${{ secrets.DEPLOY_USER }}
        REMOTE_PORT: ${{ secrets.DEPLOY_PORT }}
        SOURCE: "dist/blogging-web/"
        TARGET: ${{ secrets.DEPLOY_TARGET }}
